version: '3.8'

services:
  db:
    image: postgres:14
    environment:
      POSTGRES_DB: elevate_labs_assignment_production
      POSTGRES_USER: elevate_labs_assignment
      POSTGRES_PASSWORD: password123
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - '5432:5432'

  web:
    build: .
    ports:
      - '3000:80'
    environment:
      RAILS_MASTER_KEY: ${RAILS_MASTER_KEY}
      DATABASE_URL: postgres://elevate_labs_assignment:password123@db:5432/elevate_labs_assignment_production
      ELEVATE_LABS_ASSIGNMENT_DATABASE_PASSWORD: password123
      DATABASE_HOST: db
      DATABASE_PORT: 5432
      BILLING_SERVICE_BASE_URL: ${BILLING_SERVICE_BASE_URL}
      BILLING_SERVICE_JWT_TOKEN: ${BILLING_SERVICE_JWT_TOKEN}
      BILLING_SERVICE_CACHE_EXPIRATION_HOURS: ${BILLING_SERVICE_CACHE_EXPIRATION_HOURS}
      BILLING_SERVICE_TIMEOUT_SECONDS: ${BILLING_SERVICE_TIMEOUT_SECONDS}
      BILLING_SERVICE_OPEN_TIMEOUT_SECONDS: ${BILLING_SERVICE_OPEN_TIMEOUT_SECONDS}
      JWT_EXPIRATION_HOURS: ${JWT_EXPIRATION_HOURS}
    depends_on:
      - db
    command: ./bin/rails server -b 0.0.0.0 -p 80

volumes:
  postgres_data:
